### PR TITLE
Fixes #386 : Use <?> in preference of <Void> for no-return async calls

### LINKED ISSUE #386: Migrate void returning async methods to `CompletableFuture<?>`
Since the callers of the async equivalents of void returning methods do not by definition care about the returned value, these returns can be easily migrated to `CompletableFuture<?>`. This allows implementations of these methods to directly return a `CompletableFuture` bearing an arbitrary type without needing to remap it.

### PR DESCRIPTION
**Pull request by chrisdennis**

### CODE REVIEW

**Comment by vladimir-bukhtoyarov** [comment]
Looks very strange. Do not see a reasonable motivation to make this non-backward  compatible change.

**Comment by vladimir-bukhtoyarov** [comment]
In my understanding methods that return ```CompletableFutute<Void>``` should be called with dramatically less rate that method that names are started from "try...", so this optimization should not bring any meaningfull value, while in same time this proposed change makes API less clear.

**Comment by prasantakumar82** [comment]
I could not find any method which name start with "try" and handles the remove operation.

**Comment by vladimir-bukhtoyarov** [comment]
@prasantakumar82 

Methods like ```tryConsume``` are significantly much more used than ```remove```.  This request removes allocation of cheap object on path that is not frequently used and in same time:
* Breaks backward compatibility.
* Makes API unclear and different from CompletionStage.

So, it needs to provide serrios arguments for this pull-request.

**Pull request closed without merging**
